name: algorithms_dart_lib
version: 0.0.1
homepage: https://thinktodo.net
repository: https://github.com/thinktodo-dev/algorithms-dart-lib

dependencies:
  flutter:
    sdk: flutter
  test: ^1.15.4
  coverage: ^1.6.0

dev_dependencies:
  stack: ^0.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"